package practicapoo.interfaz;

import practicapoo.Configuracion;
import practicapoo.jugador.AlmacenDeJugadores;
import practicapoo.palabra.AlmacenDePalabras;
import practicapoo.partida.AlmacenDePartidas;

import javax.swing.*;

/**
 * Clase que genera el JFrame Base sobre el que se asientan el resto de paneles
 * Contiene la información de almacenes necesaria para que el programa funcione
 * Contiene el método main, punto de inicio de ejecución del programa
 */
public class Main extends JFrame {


    public Main() {
        Configuracion.setter("resources/configuracion.txt");
        jugadores = new AlmacenDeJugadores();
        palabras = new AlmacenDePalabras();
        partidas = new AlmacenDePartidas();
        initComponents();
        cambiarContenido(new Menu());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    private void initComponents() {
        setLocation(300,100);
        lienzo = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Lingo");
        setIconImage(new ImageIcon("resources/Logo.png").getImage());
        setResizable(false);

        javax.swing.GroupLayout lienzoLayout = new javax.swing.GroupLayout(lienzo);
        lienzo.setLayout(lienzoLayout);
        lienzoLayout.setHorizontalGroup(
                lienzoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGap(0, 850, Short.MAX_VALUE)
        );
        lienzoLayout.setVerticalGroup(
                lienzoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGap(0, 500, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(lienzo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(lienzo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }

    /**
     * Main de la Clase
     * Inicio de funcionamiento del programa
     *
     * @param args the command line arguments
     */
    public static void main(String[] args) {
        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Main().setVisible(true);
            }
        });
    }


    // Variables declaration - do not modify
    private static AlmacenDeJugadores jugadores;
    private static AlmacenDePalabras palabras;
    private static AlmacenDePartidas partidas;
    private static javax.swing.JPanel lienzo;
    // End of variables declaration


    /**
     * Método para Cambiar el contenido del panel lienzo
     *
     * @param panel Panel para poner sobre el lienzo
     */
    public static void cambiarContenido(JPanel panel) {
        panel.setSize(850, 500);
        panel.setLocation(0, 0);
        lienzo.removeAll();
        lienzo.add(panel);
        lienzo.revalidate();
        lienzo.repaint();
        panel.setFocusable(true);
        panel.grabFocus();
    }

    /**
     * Devuelve la lista de jugadores
     *
     * @return Atributo jugadores
     */
    public static AlmacenDeJugadores getJugadores() {
        return jugadores;
    }

    /**
     * Devuelve la lista de Palabras
     *
     * @return Atributo palabras
     */
    public static AlmacenDePalabras getPalabras() {
        return palabras;
    }

    /**
     * Devuelve la lista de Partidas
     *
     * @return Atributo partidas
     */
    public static AlmacenDePartidas getPartidas() {
        return partidas;
    }

    public static JPanel getLienzo() {
        return lienzo;
    }
}
