package practicapoo.interfaz;

import javax.swing.*;

import practicapoo.jugador.AlmacenDeJugadores;
import practicapoo.jugador.Jugador;


/**
 *
 * @author z3rc0
 */
public class Sesion extends javax.swing.JPanel {
    
    private Jugador jugador;
    private Main frame;
    /**
     * Crea un nuevo form de una sesión iniciada
     * @param jugador Jugador que ha iniciado sesión
     */
    public Sesion(Jugador jugador) {
        initComponents();
        this.jugador = jugador;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jugar = new javax.swing.JButton();
        cerrarSesion = new javax.swing.JButton();
        perfil = new javax.swing.JButton();
        rankings = new javax.swing.JButton();

        jugar.setFont(new java.awt.Font("Comic Sans MS", 0, 18)); // NOI18N
        jugar.setText("Jugar!");
        jugar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jugarActionPerformed(evt);
            }
        });

        cerrarSesion.setFont(new java.awt.Font("Comic Sans MS", 0, 18)); // NOI18N
        cerrarSesion.setText("Cerrar sesion");
        cerrarSesion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cerrarSesionActionPerformed(evt);
            }
        });

        perfil.setFont(new java.awt.Font("Comic Sans MS", 0, 18)); // NOI18N
        perfil.setText("Ver perfil");
        perfil.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                perfilActionPerformed(evt);
            }
        });

        rankings.setFont(new java.awt.Font("Comic Sans MS", 0, 18)); // NOI18N
        rankings.setText("Ver rankings");
        rankings.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rankingsActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(325, 325, 325)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(cerrarSesion, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(rankings, javax.swing.GroupLayout.DEFAULT_SIZE, 250, Short.MAX_VALUE)
                        .addComponent(perfil, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jugar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap(325, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(103, 103, 103)
                .addComponent(jugar, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(perfil, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(rankings, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(cerrarSesion, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(103, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void cerrarSesionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cerrarSesionActionPerformed
        Main.cambiarContenido(new Menu());
    }//GEN-LAST:event_cerrarSesionActionPerformed

    private void jugarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jugarActionPerformed
        //TODO arreglar llamada al constructor de partida
        //TODO poner atributo frame en InterfazPartida
        //Partida p = new Partida(this.jugador,null);
        //frame.cambiarContenido(p.getPalabra(0).getInterfaz());

        //frame.cambiarContenido(new InterfazPalabra5(this.jugador));

    }//GEN-LAST:event_jugarActionPerformed

    private void perfilActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_perfilActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_perfilActionPerformed

    private void rankingsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rankingsActionPerformed
        Object[] opciones = {"Victorias", "Alfabético"};
        int n = JOptionPane.showOptionDialog(Main.getLienzo(),
                "¿Cómo quieres ver el ranking?",
                "Rankings",
                JOptionPane.YES_NO_OPTION,
                JOptionPane.QUESTION_MESSAGE,
                new ImageIcon("resources/Usuario.png"),
                opciones,
                opciones[0]);
        switch(n){
            case JOptionPane.YES_OPTION -> Main.getJugadores().rankingOrdenadoPorVictorias();
            case JOptionPane.NO_OPTION -> Main.getJugadores().rankingOrdenadoPorNombre();
        }

    }//GEN-LAST:event_rankingsActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton cerrarSesion;
    private javax.swing.JButton jugar;
    private javax.swing.JButton perfil;
    private javax.swing.JButton rankings;
    // End of variables declaration//GEN-END:variables
}
